import { build } from 'vite';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { zipSync, strToU8 } from 'fflate';
import assert from 'node:assert/strict';
const root = new URL('../', import.meta.url);
const source = await readFile(new URL('Code.gs', root), 'utf8');
const version = JSON.parse(await readFile(new URL('version.json', root), 'utf8'));
assert.ok(source.includes(`const SERVER_VERSION = "${version.gasVersion}"`));
const pkg = JSON.parse(await readFile(new URL('package.json', root), 'utf8'));
assert.equal(pkg.version, version.appVersion);
await build({ configFile: new URL('vite.gas.config.ts', root).pathname });
let html = await readFile(new URL('.gas-build/gas-entry.html', root), 'utf8');
assert.ok(html.includes('/*TEACHERSIGN_BOOTSTRAP*/null'), 'Bootstrap marker missing');
html = html.replace('/*TEACHERSIGN_BOOTSTRAP*/null', '"__TEACHERSIGN_BOOTSTRAP_JSON__"');
const scripts = [...html.matchAll(/<script\b([^>]*)>[\s\S]*?<\/script>/g)];
assert.ok(scripts.every(match => !/\bsrc\s*=/.test(match[1])), 'Standalone HTML must embed all executable scripts');
const tags = html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/g, '');
assert.ok(!/<link[^>]+(?:stylesheet|modulepreload)/.test(tags), 'Standalone HTML must embed styles and modules');
await mkdir(new URL('gas/standalone/', root), { recursive: true });
await writeFile(new URL('gas/standalone/Index.html', root), html);
await writeFile(new URL('gas/standalone/Code.gs', root), source);
await writeFile(new URL('gas/TeacherSignV5.gs', root), source);
const names = ['Code.gs', 'Index.html', 'appsscript.json', '설치안내.md', 'THIRD-PARTY-LICENSES.txt'];
const files = {};
for (const name of names) files[name] = strToU8(await readFile(new URL(`gas/standalone/${name}`, root), 'utf8'));
await mkdir(new URL('artifacts/releases/', root), { recursive: true });
await writeFile(new URL('artifacts/releases/TeacherSign-GAS.zip', root), zipSync(files, { level: 9, mtime: new Date(`${version.publishedAt}T00:00:00Z`) }));
console.log(`GAS ${version.gasVersion}: Code.gs + Index.html (${html.length} characters), installation ZIP ready`);
